name: Lint

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    ci:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [lts/*]

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup node env
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
                  cache: yarn

            - name: Install dependencies
              run: yarn install --immutable

            - name: Install foundry-toolchain (Stable)
              uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Verify Foundry installation
              run: forge --version

            - name: Import Foundry wallet
              run: |
                  mkdir -p ~/.foundry/keystores
                  cast wallet import --private-key 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6 --unsafe-password 'localhost' scaffold-eth-default

            - name: Start Anvil (Foundry Local Node)
              run: nohup yarn chain > anvil.log 2>&1 &

            - name: Wait for Anvil to be ready & Capture Port
              run: |
                  for i in {1..10}; do
                      PORT=$(grep -oP '(?<=Listening on 127\.0\.0\.1:)\d+' anvil.log | tail -n 1)
                      if [[ ! -z "$PORT" ]]; then
                          echo "ANVIL_PORT=$PORT" >> $GITHUB_ENV
                          echo "Anvil is running on port $PORT"
                          exit 0
                      fi
                      echo "Waiting for Anvil to start..."
                      sleep 3
                  done
                  echo "Anvil did not start in time" && exit 1

            - name: Deploy Contracts
              env:
                  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
                  RPC_URL: http://127.0.0.1:${{ env.ANVIL_PORT }}
              run: yarn deploy --network localhost

            - name: Run nextjs lint
              run: yarn next:lint --max-warnings=0

            - name: Check typings on nextjs
              run: yarn next:check-types
